os: osx
osx_image: xcode11.3
language: swift
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle install
  - bundle exec pod install
  - cd Pods
  - xcodebuild -scheme ALLKit -destination 'platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro Max' build-for-testing test
