os: osx
osx_image: xcode10.2
language: swift
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle install
  - bundle exec pod install
  - xcodebuild -workspace Demos.xcworkspace -scheme Demos -destination 'platform=iOS Simulator,OS=12.2,name=iPhone XS Max' build-for-testing test
